database:
  path: synthetic_essays.db

output:
  directory: output

models:
  - name: ChatGPT 4o
    model: gpt-4o
    provider: openai
    temperature: 0.8
    max_tokens: 1500
  - name: Gemini 2.5 Pro
    model: gemini-2.5-pro-preview
    provider: gemini
    temperature: 0.8
    max_tokens: 1500
  - name: Claude 3.7 Sonnet
    model: claude-3-7-sonnet
    provider: anthropic
    temperature: 1.0
    max_tokens: 1500

generation:
  default_num_essays: 60
  batch_size: 5

research:
  num_seeds: 10
  perplexity_model: llama-2-70b